module.exports.products = [
  {
    product_id: 1,
    name: 'Laptop',
    brand: 'XYZ',
    price: 999.99,
    stock_quantity: 50,
  },
  {
    product_id: 2,
    name: 'Smartphone',
    brand: 'ABC',
    price: 499.99,
    stock_quantity: 100,
  },
  {
    product_id: 3,
    name: 'Headphones',
    brand: 'SoundWave',
    price: 89.99,
    stock_quantity: 75,
  },
  {
    product_id: 4,
    name: 'Digital Camera',
    brand: 'SnapShot',
    price: 349.99,
    stock_quantity: 30,
  },
  {
    product_id: 5,
    name: 'Fitness Tracker',
    brand: 'FitTech',
    price: 79.99,
    stock_quantity: 120,
  },
  {
    product_id: 6,
    name: 'Coffee Maker',
    brand: 'BrewMaster',
    price: 59.99,
    stock_quantity: 40,
  },
  {
    product_id: 7,
    name: 'Wireless Speaker',
    brand: 'EchoSound',
    price: 129.99,
    stock_quantity: 60,
  },
  {
    product_id: 8,
    name: 'Gaming Console',
    brand: 'GameMaster',
    price: 399.99,
    stock_quantity: 25,
  },
  {
    product_id: 9,
    name: 'External Hard Drive',
    brand: 'DataVault',
    price: 119.99,
    stock_quantity: 90,
  },
  {
    product_id: 10,
    name: 'Smart Watch',
    brand: 'TechWear',
    price: 149.99,
    stock_quantity: 55,
  },
];
