openapi: '3.0.1'
info:
  title: 'ProductApi'
  version: '2023-11-19 14:53:38UTC'
servers:
  - url: 'https://um54zkzc6i.execute-api.us-east-1.amazonaws.com/{basePath}'
    variables:
      basePath:
        default: ''
paths:
  /products:
    get:
      summary: Get list of products
      description: Returns full array of products
      responses:
        '200':
          description: Products list found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Internal error or transaction error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server or DB connection error

    post:
      summary: Create one product
      description: Creates product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '200':
          description: Product created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product - <title> - successfully added
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product data is invalid
        '500':
          description: Internal error or transaction error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server or DB connection error

  /products/{productId}:
    get:
      summary: Get product by ID
      description: Returns a single product
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '500':
          description: Internal Server or DB connection Error
    parameters:
      - name: 'productId'
        in: 'path'
        description: 'Generated path parameter for productId'
        required: true
        schema:
          type: 'string'

components:
  schemas:
    Product:
      required:
        - title
      type: object
      properties:
        count:
          type: integer
          example: 7
        id:
          type: string
          example: 7567ec4b-b10c-48c5-9345-fc73c48a80a2
        description:
          type: string
          example: Short Product Description2
        price:
          type: number
          example: 23.5
        title:
          type: string
          example: ProductTop
        thumbnail:
          type: string
          example: https://i.dummyjson.com/data/products/10/thumbnail.jpeg

    NewProduct:
      required:
        - title
      type: object
      properties:
        count:
          type: integer
          example: 5
        description:
          type: string
          example: Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality
        price:
          type: number
          example: 30
        title:
          type: string
          example: Eau De Perfume Spray
        thumbnail:
          type: string
          example: https://i.dummyjson.com/data/products/15/thumbnail.jpg

x-amazon-apigateway-cors:
  allowMethods:
    - '*'
  allowHeaders:
    - '*'
  maxAge: -42
  allowCredentials: false
  allowOrigins:
    - '*'
x-amazon-apigateway-importexport-version: '1.0'
