
"openapi": "3.0.0"
"info":
  "title": "Products Service API"
  "description": "Made on AWS CDK + API Gateway + Lambda"
  "version": "1.0.0"
"servers":
  -
    "url": "https://qb6966ovig.execute-api.us-east-1.amazonaws.com/prod"
"paths":
  "/products":
    "get":
      "summary": "Get a list of products"
      "responses":
        "200":
          "description": "Successful response"
          "content":
            "application/json":
              "example":
                -
                  "id": 2
                  "title": "iPhone X"
                  "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED    technology A12 Bionic chip with ..."
                  "price": 899
                  "discountPercentage": 17.94
                  "rating": 4.44
                  "stock": 34
                  "brand": "Apple"
                  "category": "smartphones"
                  "thumbnail": "https://i.dummyjson.com/data/products/2/thumbnail.jpg"
                -
                  "id": 3
                  "title": "Samsung Universe 9"
                  "description": "Samsung's new variant which goes beyond Galaxy to the Universe"
                  "price": 1249
                  "discountPercentage": 15.46
                  "rating": 4.09
                  "stock": 36
                  "brand": "Samsung"
                  "category": "smartphones"
                  "thumbnail": "https://i.dummyjson.com/data/products/3/thumbnail.jpg"
  "/products/{productId}":
    "get":
      "summary": "Get a specific product by ID"
      "parameters":
        -
          "name": "productId"
          "in": "path"
          "required": true
          "description": "ID of the product to retrieve"
          "schema":
            "type": "integer"
      "responses":
        "200":
          "description": "Successful response"
          "content":
            "application/json":
              "example":
                -
                  "id": 3
                  "title": "Samsung Universe 9"
                  "description": "Samsung's new variant which goes beyond Galaxy to the Universe"
                  "price": 1249
                  "discountPercentage": 15.46
                  "rating": 4.09
                  "stock": 36
                  "brand": "Samsung"
                  "category": "smartphones"
                  "thumbnail": "https://i.dummyjson.com/data/products/3/thumbnail.jpg"
        "404":
          "description": "Product not found"